name: stainwarpy_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - scikit-image=0.25.2
  - pip
  - pip:
      - numpy==2.2.6
      - tifffile==2025.5.10
      - imagecodecs==2025.11.11
      - scipy==1.16.3
      - "typer[all]==0.20.0"
